stripes = [
    palettegroup(
        strip("vajon.png"),
        strip("aaa.png"),
        strip("fanphibious_danger_2.png", frames=1),
        strip("menu.png", frames=16),
        strip("mygame.png", frames=1),
        strip("peronjam.png", frames=1),
        strip("tvnel_alecu.png", frames=1),
        strip("pollitos.png", frames=5),
        strip("vortris.png"),
        strip("mijuegui.png"),
        strip("vzumaki.png"),
        strip("vasura_espacial.png"),
        strip("vs.png"),
        strip("oraculo2.png"),
        strip("vailableextreme.png", frames=1),
        strip("venti808.png", frames=1),
        strip("tvnel.png", frames=1),
        strip("2bam_demo_menu.png",frames=1),
        strip("2bam_sencom.png",frames=1),
        strip("domedefander.png"),
        strip("tincho_vrunner.png",frames=2),
        strip("villalugano_games.png"),
        strip("vslogo.png"),
        strip("loviejo-3.png"),
        fullscreen("favalli.png"),
    ),
]
