stripes = [
    palettegroup(
        strip("vga_cp437.png", frames=256),
        strip("rainbow437.png", frames=256),
        strip("vga_pc734.png", frames=256),
        strip("ready.png", frames=2),
        strip("copyright.png", frames=1),
        strip("reset.png", frames=5),
        fullscreen("bg64.png"),
        fullscreen("bgspeccy.png"),
        fullscreen("vladfartylogo.png", radius=30),
    ),
    palettegroup(
        fullscreen("farty_lion.png"),
        fullscreen("farty_lionhead.png"),
    ),
    palettegroup(
        fullscreen("chanime01.png"),
        fullscreen("chanime02.png"),
        fullscreen("chanime03.png"),
        fullscreen("chanime04.png"),
        fullscreen("chanime05.png"),
        fullscreen("chanime06.png"),
        fullscreen("chanime07.png"),
        fullscreen("salto01.png"),
        fullscreen("salto02.png"),
        fullscreen("salto03.png"),
        fullscreen("salto04.png"),
        fullscreen("salto05.png"),
        fullscreen("salto06.png"),
    ),
    palettegroup(
        fullscreen("tierra.png", radius=25),
    ),
]