stripes = [
    palettegroup(
        strip("menu.png", frames=16),
        strip("credits.png", frames=32),
        strip("debug_arxels.png", frames=7),
        strip("vga_cp437.png", frames=256),
        strip("rainbow437.png", frames=256),
        strip("tinyfont_red.png", frames=256),
        strip("tinyfont_white.png", frames=256),
        strip("galaga.png", frames=12),
        strip("gameover.png"),
        fullscreen("tecno_estructuras.png"),
        fullscreen("ventilastation.png"),
        fullscreen("sves.png"),
        # fullscreen("pyformances_n0.png"),
        # fullscreen("pyformances_py.png"),
        fullscreen("menatwork.png", radius=40),
        fullscreen("rotationgrid.png"),
        fullscreen("ventilagon-empezar1.png"),
        fullscreen("ventilagon-empezar2.png"),
        strip("empeza.png", frames=1),
        strip("super-ventilagon.png", frames=1),
    ),
    palettegroup(
        fullscreen("bembi.png"),
        strip("pollitos.png", frames=5),
    ),
    palettegroup(
        fullscreen("doom.png"),
    ),
]