stripes = [
    palettegroup(
        strip("explosion2.png", frames=5),
        strip("mira.png", frames=1),
        strip("target.png", frames=1),
        strip("misil.png", frames=1),
        strip("humo.png", frames=4),
        strip("cascote.png", frames=1),
        strip("tierra.png", frames=1),
        strip("cielo.png", frames=1),
        strip("pushtostart.png", frames=1),
        strip("failed.png", frames=1),
        strip("nuke.png", frames=5),
        strip("numerals.png", frames=12),
        fullscreen("marte.png"),
        fullscreen("domo.png", radius=6),
        fullscreen("domo2.png", radius=6),
        fullscreen("domo3.png", radius=6),
        fullscreen("domo4.png", radius=6),
        fullscreen("craters.png", radius=45),
    ),
]